// <auto-generated />
using HouseOfHope.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseOfHope.API.Migrations
{
    [DbContext(typeof(LighthouseDbContext))]
    partial class LighthouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseOfHope.API.Data.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_code");

                    b.Property<string>("DonationDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("donation_type");

                    b.Property<double?>("EstimatedValue")
                        .HasColumnType("float")
                        .HasColumnName("estimated_value");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId");

                    b.HasIndex("SupporterId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("education_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationRecordId"));

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("float")
                        .HasColumnName("progress_percent");

                    b.Property<string>("RecordDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.HasKey("EducationRecordId");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("health_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecordId"));

                    b.Property<double?>("GeneralHealthScore")
                        .HasColumnType("float")
                        .HasColumnName("general_health_score");

                    b.Property<string>("RecordDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.HasKey("HealthRecordId");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("visitation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_members_present");

                    b.Property<int>("FollowUpNeeded")
                        .HasColumnType("int")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<int>("SafetyConcernsNoted")
                        .HasColumnType("int")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.Property<string>("VisitDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("IncidentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("incident_type");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("CaseConferenceDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_conference_date");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_description");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TargetDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_date");

                    b.HasKey("PlanId");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recording_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordingId"));

                    b.Property<int>("ConcernsFlagged")
                        .HasColumnType("int")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interventions_applied");

                    b.Property<int>("ProgressNoted")
                        .HasColumnType("int")
                        .HasColumnName("progress_noted");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("SessionDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("snapshot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metric_payload_json");

                    b.Property<string>("SnapshotDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snapshot_date");

                    b.HasKey("SnapshotId");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_status");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_risk_level");

                    b.Property<string>("DateOfAdmission")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_admission");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("FamilyIndigenous")
                        .HasColumnType("int")
                        .HasColumnName("family_indigenous");

                    b.Property<int>("FamilyInformalSettler")
                        .HasColumnType("int")
                        .HasColumnName("family_informal_settler");

                    b.Property<int>("FamilyIs4ps")
                        .HasColumnType("int")
                        .HasColumnName("family_is_4ps");

                    b.Property<int>("FamilyParentPwd")
                        .HasColumnType("int")
                        .HasColumnName("family_parent_pwd");

                    b.Property<int>("FamilySoloParent")
                        .HasColumnType("int")
                        .HasColumnName("family_solo_parent");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("internal_code");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("religion");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<int>("SubCatAtRisk")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<int>("SubCatChildLabor")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<int>("SubCatChildWithHiv")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<int>("SubCatCicl")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<int>("SubCatOrphaned")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<int>("SubCatOsaec")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<int>("SubCatPhysicalAbuse")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<int>("SubCatSexualAbuse")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<int>("SubCatStreetChild")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<int>("SubCatTrafficked")
                        .HasColumnType("int")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SafehouseId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("SafehouseId");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_topic");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_at");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("int")
                        .HasColumnName("donation_referrals");

                    b.Property<double?>("EngagementRate")
                        .HasColumnType("float")
                        .HasColumnName("engagement_rate");

                    b.Property<double?>("EstimatedDonationValuePhp")
                        .HasColumnType("float")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<int?>("Impressions")
                        .HasColumnType("int")
                        .HasColumnName("impressions");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_type");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform");

                    b.Property<string>("PostType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_type");

                    b.Property<int?>("Reach")
                        .HasColumnType("int")
                        .HasColumnName("reach");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentiment_tone");

                    b.HasKey("PostId");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstDonationDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("HouseOfHope.API.Data.Donation", b =>
                {
                    b.HasOne("HouseOfHope.API.Data.Supporter", "Supporter")
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("HouseOfHope.API.Data.Resident", b =>
                {
                    b.HasOne("HouseOfHope.API.Data.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
